cc_library (
	name = "saq",
	hdrs = [
		"01-max-stack.h",
	],
)

cc_test (
	name = "all_tests",
	srcs = [
		"01-max-stack_test.cc"
	],
	deps = [
		":saq",
		"@googletest//:gtest_main",
	],
)

cc_test (
	name = "current_test",
	srcs = [
		"01-max-stack_test.cc"
	],
	deps = [
		":saq",
		"@googletest//:gtest_main",
	],
)
